In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [24]:
dataset = pd.get_dummies(dataset,dtype=int, drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [26]:
# Axis = 0 (Row) By defualt, to specify the Column which is to be deleted Axis=1 should be mentioned. 
dataset = dataset.drop("User ID", axis=1)
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [28]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [30]:
independent = dataset[["Age","EstimatedSalary","Gender_Male"]]
dependent = dataset["Purchased"]

In [32]:
independent.shape

(400, 3)

In [34]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [36]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

#Here the fit.transform function Standardize the Undefined data to Defined Data and make it to be saved in X_train
X_train = sc.fit_transform(X_train)

#Here the transform function uses the process occurred in fit.transform function for the input X_test and make it to be saved in X_train
X_test = sc.transform(X_test)

X_train

array([[ 0.81203707,  0.7926083 , -0.99250926],
       [-0.96332069, -0.30625786,  1.00754728],
       [ 0.12162016,  0.7926083 ,  1.00754728],
       [-0.96332069,  0.5847147 ,  1.00754728],
       [ 0.31888214,  0.07983025,  1.00754728],
       [ 0.71340608, -1.28632769,  1.00754728],
       [-0.47016576, -0.00926701, -0.99250926],
       [-1.75236858,  0.3768211 , -0.99250926],
       [-0.66742773,  0.13922842,  1.00754728],
       [ 0.41751312,  0.31742293,  1.00754728],
       [-0.27290378,  0.07983025, -0.99250926],
       [-0.47016576,  2.36665983, -0.99250926],
       [ 0.22025115,  0.05013116,  1.00754728],
       [ 1.30519201,  2.27756258, -0.99250926],
       [ 0.81203707,  0.28772385,  1.00754728],
       [-0.27290378,  0.16892751,  1.00754728],
       [ 0.02298918, -0.54385055,  1.00754728],
       [-0.1742728 ,  0.16892751, -0.99250926],
       [-0.07564181,  0.25802476, -0.99250926],
       [ 0.02298918, -0.24685969,  1.00754728],
       [ 2.19287089,  1.14899733, -0.99250926],
       [-1.75236858,  0.3768211 , -0.99250926],
       [ 1.89697793,  0.13922842,  1.00754728],
       [ 0.41751312, -0.12806335,  1.00754728],
       [-1.16058266,  0.31742293,  1.00754728],
       [ 0.81203707,  1.4162891 ,  1.00754728],
       [-0.27290378, -0.24685969,  1.00754728],
       [-1.6537376 , -0.03896609, -0.99250926],
       [-0.96332069, -0.75174415, -0.99250926],
       [ 0.31888214,  0.52531653,  1.00754728],
       [-0.07564181, -1.07843409, -0.99250926],
       [-1.06195168,  0.61441379,  1.00754728],
       [ 0.12162016, -0.81114232,  1.00754728],
       [-0.96332069,  1.59448361,  1.00754728],
       [-0.66742773,  1.44598818, -0.99250926],
       [-1.25921365,  0.52531653,  1.00754728],
       [-0.27290378,  0.05013116, -0.99250926],
       [-0.07564181,  0.02043208,  1.00754728],
       [-0.27290378, -0.90023957,  1.00754728],
       [ 0.91066806, -1.37542494,  1.00754728],
       [-0.27290378,  2.30726166, -0.99250926],
       [ 1.00929905,  2.03996989, -0.99250926],
       [-1.16058266,  0.49561745,  1.00754728],
       [-1.25921365,  0.28772385,  1.00754728],
       [ 1.40382299,  2.03996989, -0.99250926],
       [ 1.30519201, -1.37542494,  1.00754728],
       [-0.27290378, -0.27655878, -0.99250926],
       [-0.47016576,  1.29749276, -0.99250926],
       [-0.76605872,  1.11929824,  1.00754728],
       [ 1.00929905, -1.07843409,  1.00754728],
       [ 0.31888214,  0.31742293, -0.99250926],
       [ 1.00929905,  0.7926083 , -0.99250926],
       [-0.66742773, -1.52392037,  1.00754728],
       [-0.66742773,  0.05013116, -0.99250926],
       [ 0.51614411,  1.77267812,  1.00754728],
       [ 2.0942399 ,  0.19862659, -0.99250926],
       [-1.94963056, -0.75174415, -0.99250926],
       [-0.1742728 ,  1.44598818,  1.00754728],
       [ 0.41751312,  0.61441379, -0.99250926],
       [ 0.91066806, -1.16753134, -0.99250926],
       [-1.16058266, -0.78144323, -0.99250926],
       [ 0.22025115,  0.25802476,  1.00754728],
       [ 0.81203707, -0.30625786,  1.00754728],
       [ 2.0942399 , -0.81114232, -0.99250926],
       [ 0.81203707,  0.13922842, -0.99250926],
       [-0.27290378,  0.64411287,  1.00754728],
       [-0.96332069, -0.30625786, -0.99250926],
       [ 0.22025115, -0.36565603,  1.00754728],
       [ 2.0942399 ,  2.18846532,  1.00754728],
       [ 1.89697793, -1.28632769, -0.99250926],
       [ 1.40382299, -0.92993866, -0.99250926],
       [ 0.91066806,  1.29749276, -0.99250926],
       [ 1.50245398,  2.18846532, -0.99250926],
       [-0.27290378, -1.2566286 ,  1.00754728],
       [ 1.99560891,  0.94110373, -0.99250926],
       [ 0.71340608, -0.72204506, -0.99250926],
       [-1.45647562,  0.3768211 , -0.99250926],
       [ 0.81203707, -1.37542494,  1.00754728],
       [ 0.41751312, -0.12806335,  1.00754728],
       [-0.96332069,  0.43621927, -0.99250926],
       [ 0.02298918, -0.30625786,  1.00754728],
       [-1.16058266,  0.43621927, -0.99250926],
       [-0.8646897 , -1.22692951, -0.99250926],
       [-0.07564181,  0.05013116, -0.99250926],
       [-1.55510661, -0.42505421, -0.99250926],
       [ 1.00929905, -1.01903592, -0.99250926],
       [ 1.10793003, -1.22692951,  1.00754728],
       [ 0.02298918, -0.12806335, -0.99250926],
       [-1.06195168, -1.55361946, -0.99250926],
       [ 0.81203707, -1.22692951,  1.00754728],
       [ 1.00929905,  2.12906715,  1.00754728],
       [-1.16058266, -1.55361946, -0.99250926],
       [-0.27290378,  0.82230739, -0.99250926],
       [ 0.12162016, -0.30625786, -0.99250926],
       [-1.35784464, -1.2566286 , -0.99250926],
       [-0.56879674, -1.52392037,  1.00754728],
       [ 0.81203707,  0.55501562,  1.00754728],
       [-0.27290378, -0.33595695,  1.00754728],
       [ 1.79834694, -0.27655878,  1.00754728],
       [ 0.91066806, -1.048735  ,  1.00754728],
       [ 0.22025115,  0.07983025, -0.99250926],
       [-0.56879674,  0.91140464,  1.00754728],
       [-1.85099957, -1.43482311, -0.99250926],
       [-1.25921365,  0.61441379,  1.00754728],
       [-0.27290378,  0.55501562,  1.00754728],
       [-0.96332069, -1.10813317,  1.00754728],
       [ 1.20656102, -1.4645222 , -0.99250926],
       [ 0.22025115, -0.30625786,  1.00754728],
       [ 1.20656102, -0.75174415, -0.99250926],
       [-0.27290378,  0.07983025,  1.00754728],
       [ 0.22025115,  2.15876624, -0.99250926],
       [ 0.81203707, -1.10813317, -0.99250926],
       [ 0.12162016,  0.05013116, -0.99250926],
       [-1.75236858,  0.13922842,  1.00754728],
       [-0.8646897 ,  0.16892751,  1.00754728],
       [-0.66742773,  0.19862659,  1.00754728],
       [ 0.91066806, -1.31602677,  1.00754728],
       [ 0.22025115, -0.24685969,  1.00754728],
       [-0.37153477,  1.26779367,  1.00754728],
       [ 0.02298918,  0.31742293, -0.99250926],
       [ 0.41751312,  0.16892751, -0.99250926],
       [ 0.91066806, -0.66264689, -0.99250926],
       [ 0.12162016,  0.16892751, -0.99250926],
       [-1.85099957, -1.31602677,  1.00754728],
       [-0.07564181,  0.31742293, -0.99250926],
       [-0.1742728 , -0.27655878,  1.00754728],
       [ 0.31888214, -0.51415146,  1.00754728],
       [-0.1742728 ,  1.65388178,  1.00754728],
       [ 1.00929905, -1.19723043, -0.99250926],
       [-0.1742728 ,  1.68358087, -0.99250926],
       [ 1.30519201,  1.92117355, -0.99250926],
       [-1.06195168, -0.36565603, -0.99250926],
       [ 0.02298918,  0.05013116,  1.00754728],
       [ 0.12162016, -0.24685969, -0.99250926],
       [-1.55510661, -1.2566286 , -0.99250926],
       [-0.47016576, -0.27655878, -0.99250926],
       [ 1.00929905,  0.13922842,  1.00754728],
       [ 1.99560891, -1.37542494, -0.99250926],
       [ 1.50245398,  0.07983025,  1.00754728],
       [-0.56879674,  1.4162891 , -0.99250926],
       [ 1.60108497,  0.02043208,  1.00754728],
       [-0.76605872,  0.31742293,  1.00754728],
       [ 1.99560891,  0.76290922, -0.99250926],
       [-1.16058266, -0.51415146, -0.99250926],
       [ 0.71340608,  0.28772385,  1.00754728],
       [-1.35784464, -0.42505421,  1.00754728],
       [ 0.22025115,  0.16892751,  1.00754728],
       [-0.47016576, -1.22692951, -0.99250926],
       [ 0.6147751 ,  2.06966898, -0.99250926],
       [-1.55510661, -1.52392037,  1.00754728],
       [-0.47016576, -0.54385055, -0.99250926],
       [ 0.51614411,  1.89147447, -0.99250926],
       [-1.35784464, -1.10813317, -0.99250926],
       [ 0.81203707, -1.40512403, -0.99250926],
       [-0.27290378, -0.42505421,  1.00754728],
       [ 1.60108497,  1.03020099, -0.99250926],
       [ 1.00929905,  1.47568727, -0.99250926],
       [-0.27290378, -0.48445238,  1.00754728],
       [-0.07564181,  2.21816441,  1.00754728],
       [-1.45647562, -0.09836426, -0.99250926],
       [-0.07564181,  2.01027081, -0.99250926],
       [-0.66742773, -0.33595695,  1.00754728],
       [-0.47016576, -0.8408414 , -0.99250926],
       [ 0.71340608, -1.40512403, -0.99250926],
       [-0.76605872, -1.61301763,  1.00754728],
       [-1.85099957, -1.49422128,  1.00754728],
       [ 1.10793003,  0.13922842,  1.00754728],
       [ 0.12162016,  1.56478452,  1.00754728],
       [-0.27290378,  0.10952933,  1.00754728],
       [ 0.12162016,  0.05013116,  1.00754728],
       [-1.35784464, -1.37542494,  1.00754728],
       [ 0.31888214,  0.07983025, -0.99250926],
       [-0.8646897 ,  0.40652019, -0.99250926],
       [ 1.60108497, -1.28632769, -0.99250926],
       [-0.27290378, -0.75174415, -0.99250926],
       [-0.07564181,  0.16892751,  1.00754728],
       [-0.8646897 , -0.66264689, -0.99250926],
       [-0.66742773, -0.03896609, -0.99250926],
       [ 0.41751312, -0.45475329,  1.00754728],
       [-0.76605872,  1.95087264,  1.00754728],
       [ 1.40382299,  1.32719184, -0.99250926],
       [ 1.20656102, -0.98933683, -0.99250926],
       [ 1.79834694,  1.89147447,  1.00754728],
       [-0.8646897 , -0.24685969,  1.00754728],
       [-0.76605872,  0.5847147 ,  1.00754728],
       [-1.16058266, -1.58331854,  1.00754728],
       [-0.47016576, -1.13783226,  1.00754728],
       [ 0.31888214,  0.07983025, -0.99250926],
       [-0.1742728 , -1.07843409,  1.00754728],
       [ 1.69971595,  1.65388178, -0.99250926],
       [ 1.00929905,  1.83207629, -0.99250926],
       [ 0.31888214,  0.05013116, -0.99250926],
       [-0.76605872, -0.21716061, -0.99250926],
       [-0.07564181,  0.07983025,  1.00754728],
       [ 0.31888214, -0.18746152, -0.99250926],
       [ 1.99560891, -0.66264689, -0.99250926],
       [-0.76605872,  1.38659001, -0.99250926],
       [-1.75236858, -0.60324872,  1.00754728],
       [-0.07564181,  0.13922842,  1.00754728],
       [ 0.31888214, -0.30625786,  1.00754728],
       [ 1.10793003,  0.5847147 ,  1.00754728],
       [-0.96332069,  0.28772385,  1.00754728],
       [ 1.50245398,  0.3768211 , -0.99250926],
       [ 0.22025115, -0.36565603,  1.00754728],
       [ 2.19287089, -1.048735  ,  1.00754728],
       [-0.27290378,  1.14899733,  1.00754728],
       [-1.6537376 ,  0.07983025,  1.00754728],
       [ 0.02298918,  0.05013116,  1.00754728],
       [ 0.12162016,  1.08959916,  1.00754728],
       [-0.07564181, -0.36565603, -0.99250926],
       [-1.16058266,  0.07983025, -0.99250926],
       [-0.27290378, -1.37542494, -0.99250926],
       [ 1.60108497,  1.14899733, -0.99250926],
       [-0.76605872, -1.55361946,  1.00754728],
       [ 0.12162016,  1.92117355,  1.00754728],
       [-0.8646897 , -0.78144323,  1.00754728],
       [-0.47016576, -0.78144323,  1.00754728],
       [-0.27290378, -0.92993866,  1.00754728],
       [ 0.31888214, -0.72204506,  1.00754728],
       [ 0.31888214,  0.07983025, -0.99250926],
       [ 0.12162016,  1.92117355, -0.99250926],
       [-1.06195168,  2.01027081, -0.99250926],
       [-1.6537376 , -1.58331854, -0.99250926],
       [-1.16058266, -1.10813317,  1.00754728],
       [-0.66742773, -0.09836426,  1.00754728],
       [ 0.12162016,  0.10952933, -0.99250926],
       [ 0.31888214,  0.28772385,  1.00754728],
       [ 0.91066806, -0.57354963, -0.99250926],
       [ 0.31888214, -1.16753134, -0.99250926],
       [-0.07564181,  0.70351104, -0.99250926],
       [ 2.19287089, -0.69234597, -0.99250926],
       [-1.25921365, -1.40512403,  1.00754728],
       [-0.96332069, -0.95963774, -0.99250926],
       [ 0.02298918, -0.42505421, -0.99250926],
       [-0.1742728 , -0.45475329, -0.99250926],
       [-1.75236858, -0.98933683, -0.99250926],
       [ 1.79834694,  1.03020099, -0.99250926],
       [ 0.22025115, -0.36565603,  1.00754728],
       [ 0.41751312,  1.14899733, -0.99250926],
       [-1.75236858, -1.37542494, -0.99250926],
       [ 0.22025115, -0.12806335,  1.00754728],
       [ 0.91066806, -1.4645222 ,  1.00754728],
       [-1.94963056,  0.49561745, -0.99250926],
       [-0.27290378,  0.28772385,  1.00754728],
       [ 1.89697793, -1.07843409, -0.99250926],
       [-0.37153477,  0.07983025, -0.99250926],
       [ 1.10793003, -0.90023957, -0.99250926],
       [-1.06195168, -1.13783226, -0.99250926],
       [-1.85099957,  0.02043208,  1.00754728],
       [ 0.12162016,  0.28772385, -0.99250926],
       [-1.16058266,  0.34712202,  1.00754728],
       [-1.25921365,  0.31742293,  1.00754728],
       [-0.96332069,  0.46591836, -0.99250926],
       [ 1.69971595, -0.90023957,  1.00754728],
       [ 1.20656102,  0.55501562, -0.99250926],
       [ 1.10793003,  0.55501562,  1.00754728],
       [ 1.40382299,  2.39635892,  1.00754728],
       [-0.27290378, -0.12806335, -0.99250926],
       [ 0.41751312, -0.45475329,  1.00754728],
       [-0.37153477, -0.78144323,  1.00754728],
       [-0.07564181, -0.51415146,  1.00754728],
       [ 1.00929905, -1.16753134, -0.99250926],
       [-0.8646897 , -0.78144323,  1.00754728],
       [-0.1742728 , -0.51415146,  1.00754728],
       [-1.06195168, -0.45475329, -0.99250926],
       [-1.16058266,  1.44598818, -0.99250926]])

In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV #Here cv refers to Cross Validation

#Creating a Dictionary for Playable Parameters
param_grid = {'solver':['newton-cg','lbfgs','liblinear','saga'], 'penalty':['12']}

#if refit = false then final model will be considered as Last Combination of parameter_grid like (linear,3000,scale)
#n_jobs = -1 refers to Run all the Models Parallely
#refit = True -> Best Value from the GridSearch will be saved in Grid for Model Creation
#scoring = 'f1_weighted' -> It is used for both Balanced and Imbalanced data and can be taken into account for validation instead of Precision/Recall/Accuracy
grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3, n_jobs = -1, scoring = 'f1_weighted')

#All the above steps are called "Procedure Load"

#Model Creation
grid.fit(X_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

ValueError:
All the 20 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l2', 'l1'} or None. Got '12' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l1', 'l2'} or None. Got '12' instead.

In [45]:
y_pred = grid.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[79  6]
 [ 9 40]]

In [51]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)
print(clf_report)

              precision    recall  f1-score   support

           0       0.90      0.93      0.91        85
           1       0.87      0.82      0.84        49

    accuracy                           0.89       134
   macro avg       0.88      0.87      0.88       134
weighted avg       0.89      0.89      0.89       134

In [51]:
#clf_report.__add__

In [39]:
age_input=float(input("Age:"))
salary_input=float(input("BMI:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age: 35
BMI: 40
Sex Male 0 or 1: 1

In [41]:
classifier.predict([[age_input,salary_input,sex_male_input]])

C:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [43]:
#dir(clf_report)

In [49]:
# Naming the Model with its extension .sav
import pickle
filename = "finalized_model_Logistic_classification_Assignment.sav"

#Model will be saved in respective path, once after the below Code Execution
# Keyword - wb refers to "write binary"
pickle.dump(classifier,open(filename,'wb'))

In [51]:
# Load the Saved Model and check the same to send it for Phase-02 (Deployment)
# # Keyword - rb refers to "read binary"

loaded_model=pickle.load(open("finalized_model_Logistic_classification_Assignment.sav",'rb'))
result = loaded_model.predict([[age_input,salary_input,sex_male_input]]) 
result

C:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0], dtype=int64)